extends SceneTree
const Runtime = preload("res://scripts/world/b06_tide_runtime.gd")
const Geometry = preload("res://scripts/world/b06_room_geometry.gd")
const Status = preload("res://scripts/combat/combat_status.gd")
class Health extends RefCounted:
	var maximum := 1000.0
class Actor extends Node2D:
	var actor_kind := "enemy"
	var enemy_id := "B06-M01"
	var health := Health.new()
	var status = Status.new(2)
	var alive := true
	func is_alive() -> bool: return alive
var checks := 0
var failures: Array = []
var events: Array = []
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok: failures.append(label)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var host := Node2D.new()
	root.add_child(host)
	host.position = Vector2(700,300)
	var runtime := Runtime.new()
	host.add_child(runtime)
	check(runtime.configure("L32"),"configured geometry")
	var actor := Actor.new()
	host.add_child(actor)
	actor.position = Geometry.world_point([500,500])
	check(runtime.register_actor("spawn1",actor),"actual node and CombatStatus bound")
	check(not runtime.register_actor("renamed",actor),"stable spawn identity")
	runtime.tick(10)
	check(actor.status.shield() == 100,"high entry grants ten percent shell")
	check(runtime.movement_multiplier(actor,true) == 1.12,"sea speed in actual wet polygon")
	check(runtime.movement_multiplier(actor) == .85,"player terrain multiplier")
	actor.status.absorb(50)
	runtime.tick(0)
	check(actor.status.shield() == 50,"same high cannot refill")
	var hero := Node2D.new()
	host.add_child(hero)
	hero.position = Geometry.world_point([840,990])
	runtime.drain_completed.connect(func(event: Dictionary) -> void: events.append(event))
	check(runtime.interact("drain_west",hero,"hero",func() -> bool: return true,func(_a: Vector2,_b: Vector2) -> bool: return true),"in-range F begins channel")
	runtime.tick(.59)
	check(events.is_empty(),"no premature drain")
	runtime.tick(.01)
	check(events.size() == 1 and runtime.movement_multiplier(actor) == 1.0,"completion drains only linked actual patch")
	check(not runtime.interact("drain_west",hero,"hero",func() -> bool: return true,func(_a: Vector2,_b: Vector2) -> bool: return true),"gate cooldown enforced")
	var saved := runtime.checkpoint()
	runtime.tick(2,true)
	check(runtime.checkpoint() == saved,"paused simulation freezes tide")
	check(runtime.restore_checkpoint(saved),"exact tide restore")
	var wrong := saved.duplicate(true)
	wrong.room_id = "L31"
	check(not runtime.restore_checkpoint(wrong) and runtime.checkpoint() == saved,"cross-room restore atomic")
	runtime.tick(16)
	check(runtime.interact("drain_west",hero,"hero",func() -> bool: return true,func(_a: Vector2,_b: Vector2) -> bool: return true),"reuse after cooldown")
	hero.position += Vector2(100,0)
	runtime.tick(.6)
	check(events.size() == 1,"leaving range interrupts")
	hero.position = Geometry.world_point([840,990])
	check(runtime.interact("drain_west",hero,"hero",func() -> bool: return true,func(_a: Vector2,_b: Vector2) -> bool: return true),"cancel does not spend cooldown")
	runtime.notify_actor_hit("hero",1)
	runtime.tick(.6)
	check(events.size() == 1,"confirmed hit interrupts")
	var start := Vector2(500,500)
	var poly := PackedVector2Array([Vector2(100,100),Vector2(600,100),Vector2(600,600),Vector2(100,600)])
	var end := runtime.clipped_push("hero",start,Vector2(500,0),poly)
	check(end.x < 600 and end.x > 599,"push clips at boundary")
	check(runtime.clipped_push("hero",start,Vector2(500,0),poly) == start,"second push protected")
	var market := Runtime.new()
	host.add_child(market)
	check(market.configure("L33"),"alternating market configured")
	actor.position = Geometry.world_point([1000,500])
	market.tick(10)
	check(market.movement_multiplier(actor) == .85,"market first north tide")
	actor.position = Geometry.world_point([1600,1300])
	check(market.movement_multiplier(actor) == 1,"market first south dry")
	market.tick(16)
	check(market.movement_multiplier(actor) == .85,"market next south tide")
	actor.position = Geometry.world_point([1000,500])
	check(market.movement_multiplier(actor) == 1,"market next north dry")
	var garden := Runtime.new()
	host.add_child(garden)
	check(garden.configure("L35"),"bell garden configured")
	hero.position = Geometry.world_point([1400,396])
	check(not garden.next_tide_visible(),"no unsolicited early direction")
	check(garden.reveal_next_tide(hero,func(): return true,func(_a,_b): return true),"real range bell interaction")
	check(garden.next_tide_visible() and garden.state.clock_state().phase == "low","bell reveals without advancing fixed cycle")
	var bell_saved: Dictionary = JSON.parse_string(JSON.stringify(garden.checkpoint()))
	garden.tick(1,true)
	check(JSON.parse_string(JSON.stringify(garden.checkpoint())) == bell_saved,"paused bell and tide unchanged")
	garden.tick(10)
	check(garden.restore_checkpoint(bell_saved) and garden.next_tide_visible(),"JSON bell preview restored with exact low phase")
	var bad_bell := bell_saved.duplicate(true)
	bad_bell.bell_preview = "yes"
	check(not garden.restore_checkpoint(bad_bell) and JSON.parse_string(JSON.stringify(garden.checkpoint())) == bell_saved,"corrupt bell restore atomic")
	garden.tick(10)
	check(not garden.next_tide_visible(),"bell preview consumed by high tide")
	var bay := Runtime.new()
	host.add_child(bay)
	check(bay.configure("BO06"),"boss host shares configured clock")
	check(bay.state == bay.boss_state.tide_state(),"exactly one tide object")
	hero.position = Geometry.world_point([560,900])
	check(bay.interact("drain_west",hero,"hero",func(): return true,func(_a,_b): return true),"boss drain before P2")
	bay.tick(.6)
	var pillar := Geometry.world_point([1050,650])
	var claw := {"b06_command":true,"boss_id":"BO06","action_id":"siege_claw","shape":"cone","origin":pillar+Vector2(100,0),"direction":Vector2.LEFT,"range":170.0,"angle":deg_to_rad(120),"cast_id":"claw1"}
	check(bay.confirm_boss_claw(claw),"locked claw geometric contact on drained pillar")
	check(bay.boss_state.incoming_multiplier("side_abdomen") == 1.15,"actual host opens abdomen")
	check(not bay.confirm_boss_claw(claw),"same cast cannot expose twice")
	check(bay.boss_state.set_health(int(bay.boss_state.snapshot().maximum_hp*.7)),"boss P2 starts same clock")
	bay.tick(16)
	check(not bay.can_enemy_cast() and not bay.can_enemy_hit(),"post-high full output window blocks casts and delayed hits")
	var boss_saved: Dictionary = JSON.parse_string(JSON.stringify(bay.checkpoint()))
	bay.tick(2.5)
	check(bay.can_enemy_cast(),"output window ends exactly")
	check(bay.restore_checkpoint(boss_saved) and not bay.can_enemy_hit(),"boss output/exposure checkpoint restores same clock")
	check(bay.state == bay.boss_state.tide_state(),"restored shared clock stays single")
	var shop := Runtime.new()
	host.add_child(shop)
	check(shop.configure("L32"),"geometry helper host")
	shop.tick(10)
	actor.position = Geometry.world_point([900,500])
	var dry := shop.nearest_dry_point(actor,70)
	check(dry != actor.position and dry.distance_to(actor.position) <= 70,"bounded nearby dry retreat")
	actor.position = dry
	check(shop.movement_multiplier(actor) == 1,"dry retreat actually dry")
	check(shop.tidal_direction_at(Geometry.world_point([500,500])) == Vector2.DOWN,"authored patch direction")
	check(shop.tidal_direction_at(Geometry.world_point([1400,900])) == Vector2.ZERO,"no invented dry-ground tide direction")
	check(shop.admit_coral_wall(Vector2(220,240),Vector2(340,240)),"peripheral120wall admitted")
	check(not shop.admit_coral_wall(Vector2(750,574),Vector2(870,574)),"main dry corridor cannot be walled")
	check(not shop.admit_coral_wall(Vector2(100,240),Vector2(220,240)),"wall footprint cannot leave floor")
	check(not shop.admit_coral_wall(Vector2(220,240),Vector2(341,240)),"wall authored length enforced")
	var bomb := {"action_id":"shell_bombard","shape":"circle","origin":Geometry.world_point([1400,700]),"direction":Vector2.DOWN,"target":Geometry.world_point([1400,1000]),"radius":90.0,"stage":0}
	bay.tick(2.5)
	var safe_bomb: Dictionary = bay.constrain_enemy_command(bomb)
	check(not safe_bomb.is_empty() and safe_bomb.target.distance_to(safe_bomb.b06_dry_refuge) >= 198,"bombard entire footprint avoids dry refuge")
	check(bomb.target == Geometry.world_point([1400,1000]),"warning relocation does not mutate caller")
	# Both archived and new BO06 tide states restore independently of defaults.
	for archive in [0,1,7,12,13]:
		var calibration := preload("res://scripts/combat/enemy_calibration.gd").archived(archive)
		var source := Runtime.new()
		var target := Runtime.new()
		host.add_child(source)
		host.add_child(target)
		check(source.configure("BO06",4,calibration) and target.configure("BO06",4),"versioned BO06 setup %d"%archive)
		var frozen := source.checkpoint()
		if archive==0: frozen.erase("boss_numerical") # Historical payload before provenance.
		check(target.restore_checkpoint(JSON.parse_string(JSON.stringify(frozen))),"archived BO06 restore %d"%archive)
		check(target.boss_state.snapshot().maximum_hp==source.boss_state.snapshot().maximum_hp,"archived BO06 exact HP %d"%archive)
		var before := target.checkpoint()
		var invalid := frozen.duplicate(true)
		invalid.boss_state.maximum_hp += 1
		check(not target.restore_checkpoint(invalid) and target.checkpoint()==before,"noncanonical BO06 HP rejected atomically %d"%archive)
		source.free()
		target.free()
	host.free()
	for failure in failures: printerr(failure)
	print("B06 tide runtime: %d checks, %d failures" % [checks,failures.size()])
	quit(0 if failures.is_empty() else 1)
