extends SceneTree
const Tide = preload("res://scripts/world/b06_tide_state.gd")
var checks := 0
var failures: Array[String] = []
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok: failures.append(label)
func make(room_id: String = "L32") -> RefCounted:
	var result := Tide.new()
	check(result.configure(room_id,["west","east"],{"gate_w":"west","gate_e":"east"}), "configure " + room_id)
	return result
func _initialize() -> void:
	clock_and_drain()
	shell_and_push()
	checkpoint()
	boss_and_clipping()
	for failure: String in failures: printerr("FAIL: " + failure)
	print("B06 tide state: %d checks, %d failures" % [checks,failures.size()])
	quit(0 if failures.is_empty() else 1)
func clock_and_drain() -> void:
	var tide := make("L31")
	check(tide.clock_state().phase == "low" and tide.clock_state().remaining_seconds == 12, "tutorial first low is twelve seconds")
	check(tide.advance(11.999999).events.is_empty(), "no early warning")
	check(tide.advance(.000001).events[0].event == "tide_warning", "exact warning boundary")
	check(not tide.is_wet("west"), "warning does not flood")
	check(tide.advance(2).events[0].event == "tide_high", "two full seconds of warning")
	check(tide.is_wet("west") and tide.player_movement_multiplier("west") == .85, "high tide 15 percent slow")
	check(is_equal_approx(tide.player_movement_multiplier("west", .2), .88), "U01 reduces magnitude, not 20 percentage points")
	check(is_equal_approx(tide.player_movement_multiplier("west", 1), .925), "terrain resistance cap fifty percent")
	check(tide.sea_movement_multiplier("west") == 1.12, "sea wet movement boost")
	check(tide.begin_drain("gate_w","hero"), "all classes can start drain without gear")
	check(not tide.begin_drain("gate_e","other"), "single active interaction")
	check(not tide.cancel_drain("other") and tide.cancel_drain("hero"), "cancel is actor bound")
	check(tide.begin_drain("gate_w","hero"), "cancel consumes no cooldown")
	tide.advance(.59)
	check(tide.is_wet("west"), "channel not instantaneous")
	var completion: Dictionary = tide.advance(.01)
	check(completion.events.size() == 1 and completion.events[0].event == "drain_completed", "one completion receipt")
	check(not tide.is_wet("west") and tide.is_wet("east"), "drain changes only linked patch")
	check(not tide.begin_drain("gate_w","hero"), "completed gate has sixteen second CD")
	check(tide.advance(5.4).events[0].event == "tide_low", "first cycle ends at twenty")
	check(tide.clock_state().remaining_seconds == 8, "later low uses eight seconds")
	var result: Dictionary = tide.advance(16)
	check(result.events.size() == 3 and result.events[0].event == "tide_warning" and result.events[1].event == "tide_high" and result.events[2].event == "tide_low", "large simulation step preserves event ordering")
	check(tide.begin_drain("gate_w","hero"), "gate reusable after CD")
	var fresh := make()
	fresh.advance(9.4)
	fresh.begin_drain("gate_w","hero")
	result = fresh.advance(.6)
	check(result.events.size() == 2 and result.events[0].event == "drain_completed" and result.events[1].event == "tide_high", "same-time drain completion precedes high entry")
	check(not fresh.is_wet("west") and fresh.is_wet("east"), "same-time drain prevents tidal shield eligibility")
func shell_and_push() -> void:
	var tide := make()
	check(tide.enter_high_water("fish","B06-M01","west",1000).is_empty(), "no dry shell")
	tide.advance(10)
	var shell: Dictionary = tide.enter_high_water("fish","B06-M01","west",1000,120)
	check(shell.shield == 120 and shell.seconds == 6 and shell.replace_not_add, "shield replaces higher, never stacks")
	check(tide.enter_high_water("fish","B06-M01","east",1000).is_empty(), "same actor cannot retrigger by crossing patches")
	check(tide.enter_high_water("boss","BO06","west",23760).is_empty(), "ordinary sea armor cannot shield boss")
	check(tide.enter_high_water("legacy","B05-M01","west",1000).is_empty(), "other clan cannot use shell")
	check(tide.enter_high_water("fish2","B06-M02","west",1005).shield == 101, "one half-up integer shield boundary")
	tide.advance(16)
	check(tide.enter_high_water("fish","B06-M01","west",1000).shield == 100, "new high cycle can refresh after ICD")
	check(tide.admit_push("hero",50,.25).distance == 37.5, "active shield resistance value")
	check(tide.admit_push("hero",50).distance == 0, "second displacement blocked for two seconds")
	tide.advance(1.999999)
	check(tide.admit_push("hero",50).protected, "protection lasts through final microsecond")
	tide.advance(.000001)
	check(tide.admit_push("hero",50,.7).distance == 25, "resistance caps at fifty, no permanent immunity")
	check(tide.admit_push("other",50).distance == 50, "protection isolated per actor")
func checkpoint() -> void:
	var original := make()
	original.advance(8.75)
	original.begin_drain("gate_e","hero")
	original.advance(.2)
	var encoded: Variant = JSON.parse_string(JSON.stringify(original.snapshot()))
	var restored := make()
	check(restored.restore(encoded), "warning and partial channel JSON roundtrip")
	check(restored.clock_state() == original.clock_state() and restored.clock_state().phase == "warning", "restoring warning cannot skip warning")
	check(restored.advance(1.05) == original.advance(1.05), "post-restore transition and channel completion identical")
	original.enter_high_water("fish","B06-M03","west",1000)
	original.admit_push("hero",50)
	encoded = JSON.parse_string(JSON.stringify(original.snapshot()))
	check(restored.restore(encoded), "high phase actor guards roundtrip")
	check(restored.enter_high_water("fish","B06-M03","west",1000).is_empty(), "save reload does not mint shield")
	check(restored.admit_push("hero",50).distance == 0, "save reload retains push protection")
	var stable: Dictionary = restored.snapshot()
	var mutations: Array = []
	var bad: Dictionary = stable.duplicate(true); bad.room_id = "L33"; mutations.append(bad)
	bad = stable.duplicate(true); bad.now_us = 1.5; mutations.append(bad)
	bad = stable.duplicate(true); bad.version = true; mutations.append(bad)
	bad = stable.duplicate(true); bad.tide_start_us = -1; mutations.append(bad)
	bad = stable.duplicate(true); bad.gates.gate_e = "west"; mutations.append(bad)
	bad = stable.duplicate(true); bad.gate_ready_at.gate_e = bad.now_us + 16000001; mutations.append(bad)
	bad = stable.duplicate(true); bad.drained_until.unknown = bad.now_us + 1; mutations.append(bad)
	bad = stable.duplicate(true); bad.shells.fish.cycle = 99; mutations.append(bad)
	bad = stable.duplicate(true); bad.push_ready_at.hero = bad.now_us + 2000001; mutations.append(bad)
	bad = stable.duplicate(true); bad.channel = {"actor_id":"hero"}; mutations.append(bad)
	bad = stable.duplicate(true); bad.rounding_remainder = NAN; mutations.append(bad)
	for value: Variant in mutations + [null, [], {}]:
		check(not restored.restore(value), "malformed checkpoint rejected")
		check(restored.snapshot() == stable, "restore atomic")
	for delta: float in [-1, INF, NAN, 60.01]:
		check(not restored.advance(delta).ok and restored.snapshot() == stable, "invalid simulation step atomic")
	encoded.shells.clear()
	check(not restored.snapshot().shells.is_empty(), "restored values detached")
	var fractional := make()
	for index in range(60): fractional.advance(1.0/60.0)
	check(absf(fractional.clock_state().remaining_seconds - 7.0) < .000002, "sub-microsecond accumulation does not drift")
	check(not Tide.new().configure("L30",[],{}), "foreign chapter rejected")
	check(not Tide.new().configure("L32",["west","west"],{}), "duplicate patch rejected")
	check(not Tide.new().configure("L32",["west"],{"gate":"east"}), "unknown patch link rejected")
func boss_and_clipping() -> void:
	var tide := make("BO06")
	tide.advance(30)
	check(tide.clock_state().phase == "inactive" and not tide.is_wet("west"), "boss P1 dry without hidden running tide")
	check(tide.set_boss_phase(2) and tide.clock_state().remaining_seconds == 8, "P2 starts full warning-aware cycle")
	tide.advance(9)
	var before: Dictionary = tide.clock_state()
	check(tide.set_boss_phase(3) and tide.clock_state() == before, "P3 never starts independent cycle")
	check(not tide.set_boss_phase(1), "no phase regression reset")
	var events: Array = tide.advance(7).events
	check(events.size() == 3 and events[2].event == "boss_output_window" and events[2].seconds == 2.5, "high end promises full 2.5 second window")
	var restored := make("BO06")
	check(restored.restore(JSON.parse_string(JSON.stringify(tide.snapshot()))), "boss phase and clock restore")
	var square := PackedVector2Array([Vector2(0,0),Vector2(100,0),Vector2(100,100),Vector2(0,100)])
	var clipped := Tide.clip_push(Vector2(50,50),Vector2(100,0),square)
	check(clipped.x < 100 and clipped.x > 99.9 and clipped.y == 50, "clip before navigation edge")
	check(Tide.clip_push(Vector2(50,50),Vector2(20,10),square) == Vector2(70,60), "legal displacement unchanged")
	check(Tide.clip_push(Vector2(-10,50),Vector2(100,0),square) == Vector2(-10,50), "outside origin fails closed")
	var concave := PackedVector2Array([Vector2(0,0),Vector2(100,0),Vector2(100,100),Vector2(70,100),Vector2(70,30),Vector2(30,30),Vector2(30,100),Vector2(0,100)])
	clipped = Tide.clip_push(Vector2(15,60),Vector2(70,0),concave)
	check(clipped.x < 30 and clipped.x > 29.9, "concave crossing stops at first gap, cannot teleport across water")
