extends RefCounted
## Immutable B06 generator-v4 archive. Never consult live JSON for receipts.
## Reuses v1 roll/economy weights; chapter preferences are relative, never grants.
const LEVEL_CAP := 30
const TEMPLATES := {
	"B06-SG-accessory":{"slot":"charm","race_id":"B06","affix_tendencies_by_power":{"physical":["damage_bonus","max_hp"]},"price":160,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-chest":{"slot":"chest","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","armor"]},"price":180,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-feet":{"slot":"feet","race_id":"B06","affix_tendencies_by_power":{"physical":["move_speed"]},"price":120,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-hands":{"slot":"hands","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","crit_chance"]},"price":120,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-head":{"slot":"head","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","crit_chance"]},"price":140,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-legs":{"slot":"legs","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","armor","magic_resist"]},"price":180,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-ring":{"slot":"ring","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","crit_chance"]},"price":160,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SG-weapon":{"slot":"weapon","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","damage_bonus"]},"price":180,"allowed_heroes":["CH02"],"power_types":["physical"],"set_id":"B06-SG","drop_origin":"B06","class_policy_version":3},
	"B06-SM-accessory":{"slot":"charm","race_id":"B06","affix_tendencies_by_power":{"magic":["max_mana","max_hp"]},"price":160,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-chest":{"slot":"chest","race_id":"B06","affix_tendencies_by_power":{"magic":["max_hp","magic_resist"]},"price":180,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-feet":{"slot":"feet","race_id":"B06","affix_tendencies_by_power":{"magic":["move_speed"]},"price":120,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-hands":{"slot":"hands","race_id":"B06","affix_tendencies_by_power":{"magic":["ability_power","cooldown_reduction"]},"price":120,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-head":{"slot":"head","race_id":"B06","affix_tendencies_by_power":{"magic":["max_mana","magic_resist"]},"price":140,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-legs":{"slot":"legs","race_id":"B06","affix_tendencies_by_power":{"magic":["max_hp","armor","magic_resist"]},"price":180,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-ring":{"slot":"ring","race_id":"B06","affix_tendencies_by_power":{"magic":["ability_power","resource_gain_bonus"]},"price":160,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SM-weapon":{"slot":"weapon","race_id":"B06","affix_tendencies_by_power":{"magic":["ability_power","damage_bonus"]},"price":180,"allowed_heroes":["CH03"],"power_types":["magic"],"set_id":"B06-SM","drop_origin":"B06","class_policy_version":3},
	"B06-SU-accessory":{"slot":"charm","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","damage_reduction","cooldown_reduction"],"magic":["max_hp","damage_reduction","cooldown_reduction"]},"price":160,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-chest":{"slot":"chest","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","damage_reduction"],"magic":["max_hp","damage_reduction"]},"price":180,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-feet":{"slot":"feet","race_id":"B06","affix_tendencies_by_power":{"physical":["move_speed","damage_reduction"],"magic":["move_speed","damage_reduction"]},"price":120,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-hands":{"slot":"hands","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","cooldown_reduction"],"magic":["ability_power","cooldown_reduction"]},"price":120,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-head":{"slot":"head","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","magic_resist"],"magic":["max_hp","magic_resist"]},"price":140,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-legs":{"slot":"legs","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","armor","magic_resist"],"magic":["max_hp","armor","magic_resist"]},"price":180,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-ring":{"slot":"ring","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","max_hp"],"magic":["ability_power","max_hp"]},"price":160,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SU-weapon":{"slot":"weapon","race_id":"B06","affix_tendencies_by_power":{"physical":["attack"],"magic":["ability_power"]},"price":180,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"B06-SU","drop_origin":"B06","class_policy_version":3},
	"B06-SW-accessory":{"slot":"charm","race_id":"B06","affix_tendencies_by_power":{"physical":["resource_gain_bonus","max_hp"]},"price":160,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-chest":{"slot":"chest","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","armor"]},"price":180,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-feet":{"slot":"feet","race_id":"B06","affix_tendencies_by_power":{"physical":["move_speed","damage_reduction"]},"price":120,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-hands":{"slot":"hands","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","crit_chance"]},"price":120,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-head":{"slot":"head","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","armor"]},"price":140,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-legs":{"slot":"legs","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","armor","magic_resist"]},"price":180,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-ring":{"slot":"ring","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","resource_gain_bonus"]},"price":160,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-SW-weapon":{"slot":"weapon","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","damage_bonus"]},"price":180,"allowed_heroes":["CH01"],"power_types":["physical"],"set_id":"B06-SW","drop_origin":"B06","class_policy_version":3},
	"B06-U01":{"slot":"feet","race_id":"B06","affix_tendencies_by_power":{"physical":["move_speed","damage_reduction"],"magic":["move_speed","damage_reduction"]},"price":120,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"","drop_origin":"B06","class_policy_version":3},
	"B06-U02":{"slot":"ring","race_id":"B06","affix_tendencies_by_power":{"physical":["attack","max_hp"],"magic":["ability_power","max_hp"]},"price":160,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"","drop_origin":"B06","class_policy_version":3},
	"B06-U03":{"slot":"charm","race_id":"B06","affix_tendencies_by_power":{"physical":["max_hp","damage_reduction","cooldown_reduction"],"magic":["max_hp","damage_reduction","cooldown_reduction"]},"price":160,"allowed_heroes":["CH01","CH02","CH03"],"power_types":["physical","magic"],"set_id":"","drop_origin":"B06","class_policy_version":3}
}
const PREFERENCE_WEIGHT := 2
const ROOM_PREFERRED_SLOTS := {"L31": ["head", "chest"], "L32": ["legs", "feet"], "L33": ["hands", "ring"], "L34": ["hands", "ring"], "L35": ["weapon", "charm"], "L36": ["weapon", "charm"], "BO06": ["weapon", "charm"]}
const ROOM_LEVELS := {"L31": 26, "L32": 26, "L33": 28, "L34": 28, "L35": 30, "L36": 30, "BO06": 30}
const MONSTER_PREFERRED_SLOT := {"B06-M01": "chest", "B06-M02": "head", "B06-M03": "chest", "B06-M04": "feet", "B06-M05": "ring", "B06-M06": "legs", "B06-M07": "hands", "B06-M08": "charm", "B06-M09": "weapon", "B06-M10": "head", "B06-M11": "legs", "B06-M12": "hands", "B06-M13": "ring", "B06-M14": "feet", "B06-M15": "chest", "B06-M16": "weapon", "B06-M17": "charm", "B06-M18": "charm"}
const UNIQUE_PREFERENCES := {"B06-U01": ["L32", "B06-M04", "B06-M06"], "B06-U02": ["L34", "B06-M05", "B06-M15"], "B06-U03": ["L36", "B06-M13", "B06-M18"]}
