extends SceneTree
const Boss = preload("res://scripts/levels/b06/combat/boss_state.gd")
var checks := 0
var failures: Array[String] = []
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok: failures.append(label)
func make() -> RefCounted:
	var result := Boss.new()
	check(result.configure(1000,["west","east"],{"gate_w":"west","gate_e":"east"},{"reef_w":"west","reef_e":"east"}),"configure")
	return result
func _initialize() -> void:
	phases_and_output()
	pillars()
	checkpoint()
	for failure: String in failures: printerr("FAIL: " + failure)
	print("B06 boss state: %d checks, %d failures" % [checks,failures.size()])
	quit(0 if failures.is_empty() else 1)
func phases_and_output() -> void:
	var boss := make()
	check(boss.phase() == 1 and boss.clock_state().phase == "inactive","P1 dry and inactive")
	check(boss.advance(45).events.is_empty(),"P1 does not secretly run tide")
	check(boss.damage_admitted(),"ordinary attacks initially admitted")
	check(boss.set_health(701) and boss.phase() == 1,"above seventy percent P1")
	check(boss.set_health(700) and boss.phase() == 2,"exact seventy P2")
	check(boss.clock_state().phase == "low" and boss.clock_state().remaining_seconds == 8,"P2 starts fresh eight second low")
	boss.advance(9)
	check(boss.set_health(400) and boss.phase() == 3 and boss.clock_state().remaining_seconds == 1,"P3 keeps warning clock")
	check(boss.set_health(1000) and boss.phase() == 3,"healing never regresses phase")
	check(not boss.set_health(-1) and not boss.set_health(1001),"invalid HP rejected")
	var before: Dictionary = boss.snapshot()
	check(not boss.advance(NAN).ok and not boss.advance(61).ok and boss.snapshot() == before,"invalid advance atomic")
	var events: Array = boss.advance(7).events
	check(events.size() == 3 and events[-1].event == "boss_output_window","single clock emits output window")
	check(not boss.damage_admitted(),"high end blocks damaging cast and execution")
	check(boss.incoming_multiplier("other") == 1.0,"output window does not make boss invulnerable")
	boss.advance(2.499999)
	check(not boss.damage_admitted(),"full output window through last microsecond")
	boss.advance(.000001)
	check(boss.damage_admitted(),"attack permitted exactly at 2.5 seconds")
	boss.advance(45.5)
	check(not boss.damage_admitted(),"large step latest cycle window correct")
	boss.advance(3)
	check(boss.damage_admitted(),"large step does not reopen expired earlier window")
	check(boss.begin_drain("gate_w","hero"),"active interaction before death")
	check(boss.set_health(0) and not boss.damage_admitted(),"death blocks damage")
	check(boss.snapshot().tide.channel.is_empty(),"death cancels channel without completing")
	check(not boss.set_health(10) and not boss.advance(1).ok and not boss.begin_drain("gate_e","hero"),"dead encounter cannot revive or advance")
	var skipped := make()
	check(skipped.set_health(300) and skipped.phase() == 3 and skipped.clock_state().remaining_seconds == 8,"large damage skips to P3 with one full tide clock")
func pillars() -> void:
	var boss := make()
	check(not boss.confirm_claw_pillar_contact("reef_w"),"dry low alone is not drainage")
	check(boss.begin_drain("gate_w","hero"),"drain starts")
	boss.advance(.599999)
	check(not boss.confirm_claw_pillar_contact("reef_w"),"partial channel cannot expose")
	boss.advance(.000001)
	check(not boss.confirm_claw_pillar_contact("unknown") and not boss.confirm_claw_pillar_contact("reef_e"),"pillar and drainage patch identity enforced")
	check(boss.confirm_claw_pillar_contact("reef_w"),"completed drainage permits verified claw collision")
	check(boss.exposure_remaining() == 5 and boss.incoming_multiplier("side_abdomen") == 1.15,"five second side exposure")
	check(boss.incoming_multiplier("front_shell") == .65 and boss.incoming_multiplier("other") == 1,"front armor and other regions unchanged")
	check(boss.incoming_multiplier("unverified") == -1,"unknown hit region rejected")
	check(not boss.confirm_claw_pillar_contact("reef_w"),"repeated contact cannot renew")
	boss.begin_drain("gate_e","hero")
	boss.advance(.6)
	check(not boss.confirm_claw_pillar_contact("reef_e"),"alternate pillar cannot bypass global cooldown")
	boss.advance(4.399999)
	check(boss.exposure_remaining() > 0,"last exposure microsecond")
	boss.advance(.000001)
	check(boss.exposure_remaining() == 0 and boss.incoming_multiplier("side_abdomen") == 1,"exposure expires exactly")
	boss.advance(7)
	check(not boss.confirm_claw_pillar_contact("reef_w"),"expired drainage cannot expose after CD")
	boss.advance(4)
	check(boss.begin_drain("gate_w","hero"),"gate reusable after sixteen second cooldown")
	boss.advance(.6)
	check(boss.confirm_claw_pillar_contact("reef_w"),"pillar is not consumed")
func checkpoint() -> void:
	var original := make()
	original.begin_drain("gate_w","hero")
	original.advance(.6)
	original.confirm_claw_pillar_contact("reef_w")
	var restored := make()
	check(restored.restore(JSON.parse_string(JSON.stringify(original.snapshot()))),"exposure JSON roundtrip")
	check(JSON.parse_string(JSON.stringify(restored.snapshot())) == JSON.parse_string(JSON.stringify(original.snapshot())),"all encounter state restored")
	check(restored.advance(5) == original.advance(5),"restored expiry matches")
	original.set_health(500)
	original.advance(16)
	check(restored.restore(JSON.parse_string(JSON.stringify(original.snapshot()))) and not restored.damage_admitted(),"output window survives JSON save")
	check(restored.advance(2.5) == original.advance(2.5) and restored.damage_admitted(),"restored output expiry matches")
	for field: String in ["version","maximum_hp","hp","phase","exposed_until_us","pillar_ready_at_us","output_until_us"]:
		var corrupt: Dictionary = original.snapshot()
		corrupt[field] = -1
		var before: Dictionary = restored.snapshot()
		check(not restored.restore(corrupt) and restored.snapshot() == before,"atomic rejection " + field)
	var corrupt: Dictionary = original.snapshot()
	corrupt.output_until_us = corrupt.tide.now_us + 1000000
	check(not restored.restore(corrupt),"fabricated output timer rejected")
	corrupt = original.snapshot()
	corrupt.pillars.reef_w = "east"
	check(not restored.restore(corrupt),"layout mismatch rejected")
	corrupt = original.snapshot()
	corrupt.exposed_until_us = corrupt.tide.now_us + 1000000
	check(not restored.restore(corrupt),"exposure without cooldown rejected")
	corrupt = original.snapshot()
	corrupt.tide.boss_phase = 3
	check(not restored.restore(corrupt),"split boss and tide phases rejected")
	original.set_health(0)
	check(restored.restore(JSON.parse_string(JSON.stringify(original.snapshot()))) and not restored.damage_admitted(),"dead encounter restores without revival")
